#!/bin/bash
# Automated macOS Monterey VM Setup for Ultimate-macOS-KVM
# Generated by Claude - no user interaction needed

set -e
cd "$(dirname "$0")"

echo "=== Automated macOS Monterey VM Setup ==="

# Settings
VM_NAME="macOS-Monterey"
MACOS_VERSION="monterey"
CPU_CORES=4
CPU_THREADS=2
RAM="8G"
DISK_SIZE="128G"
RESOLUTION="1920x1080"

# 1. Download macOS Recovery if not present
if [ ! -f "BaseSystem.dmg" ] && [ ! -f "BaseSystem.img" ]; then
    echo "[1/5] Downloading macOS Monterey recovery..."
    cd scripts
    python3 dlosx-arg.py --action download -s $MACOS_VERSION -o ../ --disable-progress
    cd ..
else
    echo "[1/5] macOS recovery already exists, skipping download"
fi

# 2. Convert DMG to IMG if needed
if [ -f "BaseSystem.dmg" ] && [ ! -f "BaseSystem.img" ]; then
    echo "[2/5] Converting DMG to IMG..."
    dmg2img BaseSystem.dmg BaseSystem.img
    rm -f BaseSystem.dmg BaseSystem.chunklist
else
    echo "[2/5] BaseSystem.img exists, skipping conversion"
fi

# 3. Create virtual disk
if [ ! -f "${VM_NAME}.qcow2" ]; then
    echo "[3/5] Creating ${DISK_SIZE} virtual disk..."
    qemu-img create -f qcow2 "${VM_NAME}.qcow2" $DISK_SIZE
else
    echo "[3/5] Virtual disk exists, skipping"
fi

# 4. Select OVMF files for resolution
echo "[4/5] Setting up OVMF for ${RESOLUTION}..."
OVMF_VARS="ovmf/OVMF_VARS-${RESOLUTION}.fd"
if [ ! -f "$OVMF_VARS" ]; then
    OVMF_VARS="ovmf/OVMF_VARS.fd"
fi

# 5. Generate boot script
echo "[5/5] Generating boot script..."
cat > boot-${VM_NAME}.sh << BOOTSCRIPT
#!/bin/bash
# Auto-generated boot script for ${VM_NAME}
# Run with: ./boot-${VM_NAME}.sh

REPO_PATH="\$(dirname "\$0")"

args=(
    -enable-kvm
    -m ${RAM}
    -cpu Haswell-noTSX,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check
    -smp ${CPU_THREADS},cores=${CPU_CORES},sockets=1
    -machine q35
    -device usb-ehci,id=ehci
    -device usb-kbd,bus=ehci.0
    -device usb-tablet,bus=ehci.0
    -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
    -drive if=pflash,format=raw,readonly=on,file="\${REPO_PATH}/ovmf/OVMF_CODE.fd"
    -drive if=pflash,format=raw,file="\${REPO_PATH}/${OVMF_VARS}"
    -smbios type=2
    -device ich9-intel-hda -device hda-duplex
    -device ich9-ahci,id=sata
    -drive id=OpenCoreBoot,if=none,snapshot=on,format=qcow2,file="\${REPO_PATH}/boot/OpenCore.qcow2"
    -device ide-hd,bus=sata.2,drive=OpenCoreBoot,bootindex=1
    -drive id=InstallMedia,if=none,file="\${REPO_PATH}/BaseSystem.img",format=raw
    -device ide-hd,bus=sata.3,drive=InstallMedia
    -drive id=MacHDD,if=none,file="\${REPO_PATH}/${VM_NAME}.qcow2",format=qcow2
    -device ide-hd,bus=sata.4,drive=MacHDD
    -netdev user,id=net0,hostfwd=tcp::2222-:22 -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27
    -monitor stdio
    -device vmware-svga
    -display gtk,zoom-to-fit=on
)

qemu-system-x86_64 "\${args[@]}"
BOOTSCRIPT

chmod +x boot-${VM_NAME}.sh

echo ""
echo "=== Setup Complete ==="
echo "To start the VM, run: ./boot-${VM_NAME}.sh"
echo ""
echo "Inside the VM:"
echo "1. Select 'macOS Base System' from OpenCore"
echo "2. Open Disk Utility > Format disk as APFS"
echo "3. Install macOS Monterey"
echo "4. IMPORTANT: Enable auto-login after setup to prevent boot loops"
